# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import commons_pb2 as commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0emodule.service\x1a\rcommons.proto\"\x85\x03\n\x07Request\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.module.service.Request.Type\x12\x16\n\tmodule_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x06tensor\x18\x03 \x01(\x0b\x32\x07.TensorH\x01\x88\x01\x01\x12;\n\nparameters\x18\x04 \x03(\x0b\x32\'.module.service.Request.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8e\x01\n\x04Type\x12\x0b\n\x07\x46ORWARD\x10\x00\x12\t\n\x05\x41\x42ORT\x10\x01\x12\x0e\n\nGET_STATUS\x10\x02\x12\x0f\n\x0bGET_MODULES\x10\x03\x12\x0e\n\nGET_MODULE\x10\x04\x12\x13\n\x0fREGISTER_MODULE\x10\x05\x12\x15\n\x11\x44\x45REGISTER_MODULE\x10\x06\x12\x11\n\rUPDATE_MODULE\x10\x07\x42\x0c\n\n_module_idB\t\n\x07_tensor\"\xec\x01\n\x08Response\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.module.service.Response.Type\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tmodule_id\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x06tensor\x18\x04 \x01(\x0b\x32\x07.TensorH\x02\x88\x01\x01\x12\x1c\n\x06status\x18\x05 \x01(\x0e\x32\x07.StatusH\x03\x88\x01\x01\"\x19\n\x04Type\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x42\n\n\x08_messageB\x0c\n\n_module_idB\t\n\x07_tensorB\t\n\x07_status2H\n\x06Module\x12>\n\x07\x65xecute\x12\x17.module.service.Request\x1a\x18.module.service.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST_PARAMETERSENTRY']._options = None
  _globals['_REQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_REQUEST']._serialized_start=49
  _globals['_REQUEST']._serialized_end=438
  _globals['_REQUEST_PARAMETERSENTRY']._serialized_start=219
  _globals['_REQUEST_PARAMETERSENTRY']._serialized_end=268
  _globals['_REQUEST_TYPE']._serialized_start=271
  _globals['_REQUEST_TYPE']._serialized_end=413
  _globals['_RESPONSE']._serialized_start=441
  _globals['_RESPONSE']._serialized_end=677
  _globals['_RESPONSE_TYPE']._serialized_start=604
  _globals['_RESPONSE_TYPE']._serialized_end=629
  _globals['_MODULE']._serialized_start=679
  _globals['_MODULE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
